repos:
  # Ruff configuration (latest version)
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.11.2
    hooks:
      - id: ruff
        args: ['--fix']
        language_version: python3.11

  # Black configuration (use a stable release)
  - repo: https://github.com/psf/black
    rev: 25.1.0  # Use a known stable release tag
    hooks:
      - id: black
        language_version: python3.11

  # Mypy configuration (latest version)
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.15.0
    hooks:
      - id: mypy
        args: ["--exclude", ".*venv.*|.*bin.*"]
