repos:
  # Ruff configuration (latest version)
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.11.6
    hooks:
      - id: ruff
        args: ['--fix']
        language_version: python3.11

  # Black configuration (use a stable release)
  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
      - id: black
        language_version: python3.11

  # Mypy configuration (warn-only mode)
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.15.0
    hooks:
      - id: mypy
        args: ["--exclude", ".*venv.*|.*bin.*"]
        continue_on_error: true
        always_run: true
        pass_filenames: false
        language_version: python3.11

  # Useful generic checks (recommended for all repos)
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: end-of-file-fixer
      - id: trailing-whitespace

  # YAML linter (optional, but helps for configs)
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.32.0
    hooks:
      - id: yamllint
