repos:
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.0.129
    hooks:
      - id: ruff
        args: ['--fix']

  - repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
      - id: black

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.15.0
    hooks:
      - id: mypy
        args: ["--exclude", ".*venv.*|.*bin.*"]