- name: Set up Python
  uses: actions/setup-python@v5
  with:
    python-version: "3.11"

- name: Verify Python installation
  run: python --version

- name: Create Virtual Environment
  run: |
    python -m venv venv
    echo "VIRTUAL_ENV=$PWD/venv" >> $GITHUB_ENV
    echo "$PWD/venv/bin" >> $GITHUB_PATH

- name: Activate Virtual Environment and Install Dependencies
  run: |
    source venv/bin/activate
    python -m pip install --upgrade pip
    pip install -r requirements.txt
